"""empty message

Revision ID: 46d5cab020a9
Revises: 5480e89aec76
Create Date: 2016-06-29 16:14:34.296353

"""

# revision identifiers, used by Alembic.
revision = '46d5cab020a9'
down_revision = '5480e89aec76'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'areas', 'districts', ['district_id'], ['id'])
    op.create_foreign_key(None, 'communities', 'areas', ['position_id'], ['id'])
    op.add_column('houses', sa.Column('decoration', sa.SmallInteger(), nullable=True))
    op.add_column('houses', sa.Column('toward', sa.SmallInteger(), nullable=True))
    op.add_column('houses', sa.Column('type', sa.SmallInteger(), nullable=True))
    op.drop_index('ix_houses_decorate', table_name='houses')
    op.drop_index('ix_houses_kinds', table_name='houses')
    op.create_foreign_key(None, 'houses', 'communities', ['community_id'], ['id'])
    op.create_foreign_key(None, 'houses', 'users', ['author_id'], ['id'])
    op.drop_column('houses', 'kinds')
    op.drop_column('houses', 'direction')
    op.drop_column('houses', 'decorate')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('decorate', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('houses', sa.Column('direction', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('houses', sa.Column('kinds', mysql.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'houses', type_='foreignkey')
    op.drop_constraint(None, 'houses', type_='foreignkey')
    op.create_index('ix_houses_kinds', 'houses', ['kinds'], unique=False)
    op.create_index('ix_houses_decorate', 'houses', ['decorate'], unique=False)
    op.drop_column('houses', 'type')
    op.drop_column('houses', 'toward')
    op.drop_column('houses', 'decoration')
    op.drop_constraint(None, 'communities', type_='foreignkey')
    op.drop_constraint(None, 'areas', type_='foreignkey')
    ### end Alembic commands ###
