"""empty message

Revision ID: 48ce8760da22
Revises: fdd88f15f815
Create Date: 2016-07-06 15:48:33.591371

"""

# revision identifiers, used by Alembic.
revision = '48ce8760da22'
down_revision = 'fdd88f15f815'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'areas', 'districts', ['district_id'], ['id'])
    op.add_column('communities', sa.Column('area_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'communities', 'areas', ['area_id'], ['id'])
    op.drop_column('communities', 'position_id')
    op.create_foreign_key(None, 'houses', 'communities', ['community_id'], ['id'])
    op.create_foreign_key(None, 'houses', 'users', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'houses', type_='foreignkey')
    op.drop_constraint(None, 'houses', type_='foreignkey')
    op.add_column('communities', sa.Column('position_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'communities', type_='foreignkey')
    op.drop_column('communities', 'area_id')
    op.drop_constraint(None, 'areas', type_='foreignkey')
    ### end Alembic commands ###
