"""empty message

Revision ID: a710ff850665
Revises: 515bc2b61454
Create Date: 2016-06-28 16:48:25.519879

"""

# revision identifiers, used by Alembic.
revision = 'a710ff850665'
down_revision = '515bc2b61454'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=True),
    sa.Column('completion_time', sa.DateTime(), nullable=True),
    sa.Column('kinds', sa.String(length=64), nullable=True),
    sa.Column('decorate', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.String(length=64), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('total_floor', sa.Integer(), nullable=True),
    sa.Column('shi', sa.Integer(), nullable=True),
    sa.Column('ting', sa.Integer(), nullable=True),
    sa.Column('wei', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('total_area', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Integer(), nullable=True),
    sa.Column('down_payment', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('hot', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_houses_decorate'), 'houses', ['decorate'], unique=False)
    op.create_index(op.f('ix_houses_kinds'), 'houses', ['kinds'], unique=False)
    op.create_index(op.f('ix_houses_timestamp'), 'houses', ['timestamp'], unique=False)
    op.drop_table('posts')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('detail', mysql.TEXT(), nullable=True),
    sa.Column('hot', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.drop_index(op.f('ix_houses_timestamp'), table_name='houses')
    op.drop_index(op.f('ix_houses_kinds'), table_name='houses')
    op.drop_index(op.f('ix_houses_decorate'), table_name='houses')
    op.drop_table('houses')
    op.drop_table('communities')
    op.drop_table('areas')
    op.drop_table('districts')
    ### end Alembic commands ###
