"""empty message

Revision ID: b862458f0b4c
Revises: 79eaf5595f51
Create Date: 2016-08-12 13:34:17.709143

"""

# revision identifiers, used by Alembic.
revision = 'b862458f0b4c'
down_revision = '79eaf5595f51'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('en_name', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'areas', 'districts', ['district_id'], ['id'])
    op.add_column('communities', sa.Column('en_name', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'communities', 'areas', ['area_id'], ['id'])
    op.add_column('districts', sa.Column('en_name', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'houses', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'houses', 'communities', ['community_id'], ['id'])
    op.create_foreign_key(None, 'images', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'images', 'houses', ['house_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_constraint(None, 'houses', type_='foreignkey')
    op.drop_constraint(None, 'houses', type_='foreignkey')
    op.drop_column('districts', 'en_name')
    op.drop_constraint(None, 'communities', type_='foreignkey')
    op.drop_column('communities', 'en_name')
    op.drop_constraint(None, 'areas', type_='foreignkey')
    op.drop_column('areas', 'en_name')
    ### end Alembic commands ###
