"""empty message

Revision ID: c7e5cd05478d
Revises: 7a87619b9688
Create Date: 2016-08-23 13:19:56.295743

"""

# revision identifiers, used by Alembic.
revision = 'c7e5cd05478d'
down_revision = '7a87619b9688'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'areas', 'districts', ['district_id'], ['id'])
    op.add_column('communities', sa.Column('developer', sa.String(length=64), nullable=True))
    op.add_column('communities', sa.Column('greening_rate', sa.Float(), nullable=True))
    op.add_column('communities', sa.Column('property_costs', sa.Float(), nullable=True))
    op.add_column('communities', sa.Column('property_management', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'communities', 'areas', ['area_id'], ['id'])
    op.add_column('houses', sa.Column('building_age', sa.SmallInteger(), nullable=True))
    op.create_foreign_key(None, 'houses', 'communities', ['community_id'], ['id'])
    op.create_foreign_key(None, 'houses', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'images', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'images', 'houses', ['house_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_constraint(None, 'houses', type_='foreignkey')
    op.drop_constraint(None, 'houses', type_='foreignkey')
    op.drop_column('houses', 'building_age')
    op.drop_constraint(None, 'communities', type_='foreignkey')
    op.drop_column('communities', 'property_management')
    op.drop_column('communities', 'property_costs')
    op.drop_column('communities', 'greening_rate')
    op.drop_column('communities', 'developer')
    op.drop_constraint(None, 'areas', type_='foreignkey')
    ### end Alembic commands ###
