"""empty message

Revision ID: cb40553035fc
Revises: 46d5cab020a9
Create Date: 2016-06-30 11:55:45.226318

"""

# revision identifiers, used by Alembic.
revision = 'cb40553035fc'
down_revision = '46d5cab020a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'areas', 'districts', ['district_id'], ['id'])
    op.create_foreign_key(None, 'communities', 'areas', ['position_id'], ['id'])
    op.create_foreign_key(None, 'houses', 'communities', ['community_id'], ['id'])
    op.create_foreign_key(None, 'houses', 'users', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'houses', type_='foreignkey')
    op.drop_constraint(None, 'houses', type_='foreignkey')
    op.drop_constraint(None, 'communities', type_='foreignkey')
    op.drop_constraint(None, 'areas', type_='foreignkey')
    ### end Alembic commands ###
